/* ═══════════════════════════════════════════════════
   THE BET — Team & Game Data
   2026 D1 CFB Season Projections
   ═══════════════════════════════════════════════════ */

const TEAMS = {
  ohio_state: {
    id: "ohio_state",
    name: "Ohio State",
    abbreviation: "OSU",
    mascot: "Buckeyes",
    conference: "Big Ten",
    color: "#BB0000",
    wins: 11, losses: 1,
    rating: 97, offensiveRating: 98, defensiveRating: 95, spRating: 28.4,
    recruitingRank: 1,
    coachName: "Ryan Day", coachRecord: "71-9",
    stats: {
      pointsPerGame: 44.2, pointsAllowedPerGame: 13.1,
      yardsPerGame: 512.3, yardsAllowedPerGame: 278.4,
      passingYardsPerGame: 318.7, rushingYardsPerGame: 193.6,
      turnoversPerGame: 0.8, turnoversForced: 2.1,
      thirdDownPct: 0.52, redZonePct: 0.91,
      sacks: 3.4, sacksAllowed: 1.2,
    },
  },
  georgia: {
    id: "georgia",
    name: "Georgia",
    abbreviation: "UGA",
    mascot: "Bulldogs",
    conference: "SEC",
    color: "#BA0C2F",
    wins: 12, losses: 0,
    rating: 98, offensiveRating: 93, defensiveRating: 99, spRating: 30.1,
    recruitingRank: 2,
    coachName: "Kirby Smart", coachRecord: "98-18",
    stats: {
      pointsPerGame: 42.8, pointsAllowedPerGame: 10.3,
      yardsPerGame: 478.2, yardsAllowedPerGame: 244.1,
      passingYardsPerGame: 268.4, rushingYardsPerGame: 209.8,
      turnoversPerGame: 0.6, turnoversForced: 2.4,
      thirdDownPct: 0.49, redZonePct: 0.89,
      sacks: 4.1, sacksAllowed: 1.0,
    },
  },
  alabama: {
    id: "alabama",
    name: "Alabama",
    abbreviation: "ALA",
    mascot: "Crimson Tide",
    conference: "SEC",
    color: "#9E1B32",
    wins: 10, losses: 2,
    rating: 92, offensiveRating: 93, defensiveRating: 90, spRating: 22.8,
    recruitingRank: 3,
    coachName: "Kalen DeBoer", coachRecord: "24-4",
    stats: {
      pointsPerGame: 38.6, pointsAllowedPerGame: 19.2,
      yardsPerGame: 468.7, yardsAllowedPerGame: 312.4,
      passingYardsPerGame: 298.3, rushingYardsPerGame: 170.4,
      turnoversPerGame: 1.0, turnoversForced: 1.8,
      thirdDownPct: 0.47, redZonePct: 0.85,
      sacks: 2.8, sacksAllowed: 1.7,
    },
  },
  texas: {
    id: "texas",
    name: "Texas",
    abbreviation: "TEX",
    mascot: "Longhorns",
    conference: "SEC",
    color: "#BF5700",
    wins: 10, losses: 2,
    rating: 91, offensiveRating: 92, defensiveRating: 88, spRating: 21.3,
    recruitingRank: 4,
    coachName: "Steve Sarkisian", coachRecord: "36-18",
    stats: {
      pointsPerGame: 40.1, pointsAllowedPerGame: 21.4,
      yardsPerGame: 489.2, yardsAllowedPerGame: 334.7,
      passingYardsPerGame: 312.8, rushingYardsPerGame: 176.4,
      turnoversPerGame: 1.1, turnoversForced: 1.7,
      thirdDownPct: 0.48, redZonePct: 0.86,
      sacks: 2.6, sacksAllowed: 1.9,
    },
  },
  notre_dame: {
    id: "notre_dame",
    name: "Notre Dame",
    abbreviation: "ND",
    mascot: "Fighting Irish",
    conference: "Independent",
    color: "#0C2340",
    wins: 11, losses: 1,
    rating: 93, offensiveRating: 90, defensiveRating: 94, spRating: 24.2,
    recruitingRank: 6,
    coachName: "Marcus Freeman", coachRecord: "36-14",
    stats: {
      pointsPerGame: 36.4, pointsAllowedPerGame: 15.8,
      yardsPerGame: 441.3, yardsAllowedPerGame: 268.9,
      passingYardsPerGame: 248.7, rushingYardsPerGame: 192.6,
      turnoversPerGame: 0.9, turnoversForced: 2.0,
      thirdDownPct: 0.46, redZonePct: 0.88,
      sacks: 3.0, sacksAllowed: 1.4,
    },
  },
  penn_state: {
    id: "penn_state",
    name: "Penn State",
    abbreviation: "PSU",
    mascot: "Nittany Lions",
    conference: "Big Ten",
    color: "#041E42",
    wins: 10, losses: 2,
    rating: 89, offensiveRating: 86, defensiveRating: 92, spRating: 19.7,
    recruitingRank: 8,
    coachName: "James Franklin", coachRecord: "98-46",
    stats: {
      pointsPerGame: 33.2, pointsAllowedPerGame: 17.4,
      yardsPerGame: 408.4, yardsAllowedPerGame: 282.1,
      passingYardsPerGame: 234.7, rushingYardsPerGame: 173.7,
      turnoversPerGame: 1.0, turnoversForced: 1.9,
      thirdDownPct: 0.43, redZonePct: 0.84,
      sacks: 3.2, sacksAllowed: 1.6,
    },
  },
  michigan: {
    id: "michigan",
    name: "Michigan",
    abbreviation: "MICH",
    mascot: "Wolverines",
    conference: "Big Ten",
    color: "#00274C",
    wins: 9, losses: 3,
    rating: 85, offensiveRating: 83, defensiveRating: 88, spRating: 15.2,
    recruitingRank: 12,
    coachName: "Sherrone Moore", coachRecord: "14-8",
    stats: {
      pointsPerGame: 29.8, pointsAllowedPerGame: 20.1,
      yardsPerGame: 378.2, yardsAllowedPerGame: 298.4,
      passingYardsPerGame: 198.4, rushingYardsPerGame: 179.8,
      turnoversPerGame: 1.2, turnoversForced: 1.6,
      thirdDownPct: 0.41, redZonePct: 0.82,
      sacks: 2.7, sacksAllowed: 1.8,
    },
  },
  clemson: {
    id: "clemson",
    name: "Clemson",
    abbreviation: "CLEM",
    mascot: "Tigers",
    conference: "ACC",
    color: "#F56600",
    wins: 10, losses: 2,
    rating: 88, offensiveRating: 86, defensiveRating: 90, spRating: 17.9,
    recruitingRank: 9,
    coachName: "Dabo Swinney", coachRecord: "174-50",
    stats: {
      pointsPerGame: 35.7, pointsAllowedPerGame: 18.3,
      yardsPerGame: 432.8, yardsAllowedPerGame: 290.7,
      passingYardsPerGame: 258.4, rushingYardsPerGame: 174.4,
      turnoversPerGame: 1.0, turnoversForced: 1.8,
      thirdDownPct: 0.45, redZonePct: 0.86,
      sacks: 2.9, sacksAllowed: 1.5,
    },
  },
  lsu: {
    id: "lsu",
    name: "LSU",
    abbreviation: "LSU",
    mascot: "Tigers",
    conference: "SEC",
    color: "#461D7C",
    wins: 9, losses: 3,
    rating: 87, offensiveRating: 91, defensiveRating: 82, spRating: 16.4,
    recruitingRank: 5,
    coachName: "Brian Kelly", coachRecord: "48-18",
    stats: {
      pointsPerGame: 41.3, pointsAllowedPerGame: 24.7,
      yardsPerGame: 501.2, yardsAllowedPerGame: 358.4,
      passingYardsPerGame: 324.8, rushingYardsPerGame: 176.4,
      turnoversPerGame: 1.3, turnoversForced: 1.5,
      thirdDownPct: 0.50, redZonePct: 0.88,
      sacks: 2.4, sacksAllowed: 2.1,
    },
  },
  oregon: {
    id: "oregon",
    name: "Oregon",
    abbreviation: "ORE",
    mascot: "Ducks",
    conference: "Big Ten",
    color: "#154733",
    wins: 11, losses: 1,
    rating: 94, offensiveRating: 95, defensiveRating: 92, spRating: 25.8,
    recruitingRank: 7,
    coachName: "Dan Lanning", coachRecord: "42-8",
    stats: {
      pointsPerGame: 43.7, pointsAllowedPerGame: 16.8,
      yardsPerGame: 498.4, yardsAllowedPerGame: 272.3,
      passingYardsPerGame: 302.4, rushingYardsPerGame: 196.0,
      turnoversPerGame: 0.7, turnoversForced: 2.0,
      thirdDownPct: 0.51, redZonePct: 0.90,
      sacks: 3.3, sacksAllowed: 1.3,
    },
  },
  tennessee: {
    id: "tennessee",
    name: "Tennessee",
    abbreviation: "TENN",
    mascot: "Volunteers",
    conference: "SEC",
    color: "#FF8200",
    wins: 8, losses: 4,
    rating: 83, offensiveRating: 86, defensiveRating: 79, spRating: 11.9,
    recruitingRank: 11,
    coachName: "Josh Heupel", coachRecord: "48-22",
    stats: {
      pointsPerGame: 37.4, pointsAllowedPerGame: 26.8,
      yardsPerGame: 488.7, yardsAllowedPerGame: 384.2,
      passingYardsPerGame: 318.4, rushingYardsPerGame: 170.3,
      turnoversPerGame: 1.4, turnoversForced: 1.4,
      thirdDownPct: 0.48, redZonePct: 0.84,
      sacks: 2.2, sacksAllowed: 2.3,
    },
  },
  miami: {
    id: "miami",
    name: "Miami",
    abbreviation: "MIA",
    mascot: "Hurricanes",
    conference: "ACC",
    color: "#005030",
    wins: 11, losses: 1,
    rating: 90, offensiveRating: 92, defensiveRating: 87, spRating: 20.4,
    recruitingRank: 10,
    coachName: "Mario Cristobal", coachRecord: "26-14",
    stats: {
      pointsPerGame: 39.8, pointsAllowedPerGame: 19.7,
      yardsPerGame: 472.1, yardsAllowedPerGame: 304.8,
      passingYardsPerGame: 288.4, rushingYardsPerGame: 183.7,
      turnoversPerGame: 0.9, turnoversForced: 1.9,
      thirdDownPct: 0.47, redZonePct: 0.87,
      sacks: 2.8, sacksAllowed: 1.6,
    },
  },
};

const GAMES = [
  {
    id: "game_001", season: 2026, week: 1,
    date: "2026-09-05", time: "3:30 PM",
    homeTeamId: "ohio_state", awayTeamId: "texas",
    neutralSite: false, venue: "Ohio Stadium", venueCity: "Columbus, OH",
    conference: "Big Ten", isConferenceGame: false, network: "FOX",
    status: "scheduled",
    bettingLines: { spread: -14.5, total: 58.5, homeMoneyline: -620, awayMoneyline: 460, provider: "Caesars" },
  },
  {
    id: "game_002", season: 2026, week: 1,
    date: "2026-09-05", time: "7:30 PM",
    homeTeamId: "georgia", awayTeamId: "clemson",
    neutralSite: false, venue: "Sanford Stadium", venueCity: "Athens, GA",
    conference: "SEC", isConferenceGame: false, network: "ABC",
    status: "scheduled",
    bettingLines: { spread: -10.5, total: 53.5, homeMoneyline: -450, awayMoneyline: 340, provider: "DraftKings" },
  },
  {
    id: "game_003", season: 2026, week: 1,
    date: "2026-09-06", time: "12:00 PM",
    homeTeamId: "alabama", awayTeamId: "michigan",
    neutralSite: false, venue: "Bryant-Denny Stadium", venueCity: "Tuscaloosa, AL",
    conference: "SEC", isConferenceGame: false, network: "ESPN",
    status: "scheduled",
    bettingLines: { spread: -9.5, total: 51.5, homeMoneyline: -380, awayMoneyline: 290, provider: "FanDuel" },
  },
  {
    id: "game_004", season: 2026, week: 1,
    date: "2026-09-06", time: "7:30 PM",
    homeTeamId: "oregon", awayTeamId: "notre_dame",
    neutralSite: false, venue: "Autzen Stadium", venueCity: "Eugene, OR",
    conference: "Big Ten", isConferenceGame: false, network: "NBC",
    status: "scheduled",
    bettingLines: { spread: -4.5, total: 57.5, homeMoneyline: -195, awayMoneyline: 162, provider: "BetMGM" },
  },
  {
    id: "game_005", season: 2026, week: 2,
    date: "2026-09-12", time: "3:30 PM",
    homeTeamId: "lsu", awayTeamId: "tennessee",
    neutralSite: false, venue: "Tiger Stadium", venueCity: "Baton Rouge, LA",
    conference: "SEC", isConferenceGame: true, network: "ESPN",
    status: "scheduled",
    bettingLines: { spread: -3.5, total: 62.5, homeMoneyline: -172, awayMoneyline: 144, provider: "Caesars" },
  },
  {
    id: "game_006", season: 2026, week: 2,
    date: "2026-09-12", time: "8:00 PM",
    homeTeamId: "miami", awayTeamId: "penn_state",
    neutralSite: false, venue: "Hard Rock Stadium", venueCity: "Miami Gardens, FL",
    conference: "ACC", isConferenceGame: false, network: "ESPN2",
    status: "scheduled",
    bettingLines: { spread: -3.0, total: 55.5, homeMoneyline: -158, awayMoneyline: 132, provider: "DraftKings" },
  },
  {
    id: "game_007", season: 2026, week: 3,
    date: "2026-09-19", time: "7:30 PM",
    homeTeamId: "georgia", awayTeamId: "alabama",
    neutralSite: false, venue: "Sanford Stadium", venueCity: "Athens, GA",
    conference: "SEC", isConferenceGame: true, network: "CBS",
    status: "scheduled",
    bettingLines: { spread: -7.5, total: 49.5, homeMoneyline: -310, awayMoneyline: 248, provider: "Caesars" },
  },
  {
    id: "game_008", season: 2026, week: 3,
    date: "2026-09-19", time: "3:30 PM",
    homeTeamId: "notre_dame", awayTeamId: "michigan",
    neutralSite: false, venue: "Notre Dame Stadium", venueCity: "South Bend, IN",
    conference: "Independent", isConferenceGame: false, network: "NBC",
    status: "scheduled",
    bettingLines: { spread: -8.5, total: 47.5, homeMoneyline: -350, awayMoneyline: 275, provider: "BetMGM" },
  },
];

const KEY_PLAYERS = [
  { id: "p001", name: "Will Howard",    position: "QB", teamId: "ohio_state",  year: "SR", number: "18", injuryStatus: "healthy", impact: "high",
    stats: { passingYards: 3712, passingTDs: 34, interceptions: 6, completionPct: 72.4, qbr: 88.2 } },
  { id: "p002", name: "Gunner Stockton",position: "QB", teamId: "georgia",     year: "JR", number: "14", injuryStatus: "healthy", impact: "high",
    stats: { passingYards: 3284, passingTDs: 28, interceptions: 5, completionPct: 68.9, qbr: 84.7 } },
  { id: "p003", name: "Arch Manning",   position: "QB", teamId: "texas",       year: "JR", number: "16", injuryStatus: "healthy", impact: "high",
    stats: { passingYards: 3547, passingTDs: 31, interceptions: 4, completionPct: 70.2, qbr: 91.4 } },
  { id: "p004", name: "Dillon Gabriel", position: "QB", teamId: "oregon",      year: "SR", number: "8",  injuryStatus: "healthy", impact: "high",
    stats: { passingYards: 3891, passingTDs: 36, interceptions: 5, completionPct: 73.8, qbr: 92.1 } },
  { id: "p005", name: "CJ Carr",        position: "QB", teamId: "notre_dame",  year: "SO", number: "7",  injuryStatus: "questionable", impact: "high",
    stats: { passingYards: 3021, passingTDs: 24, interceptions: 7, completionPct: 65.4, qbr: 79.3 } },
  { id: "p006", name: "Jalen Milroe",   position: "QB", teamId: "alabama",     year: "SR", number: "4",  injuryStatus: "healthy", impact: "high",
    stats: { passingYards: 3198, passingTDs: 27, interceptions: 8, completionPct: 64.8, qbr: 81.2 } },
];

const MODEL_RECORD = {
  season: 2025,
  straightUp:  { wins: 142, losses: 38, pct: 0.789 },
  atsRecord:   { wins: 98,  losses: 72, pushes: 10, pct: 0.576 },
  totalRecord: { wins: 101, losses: 69, pushes: 10, pct: 0.594 },
  roi: 12.4,
};

/* helper to resolve game teams */
function resolveGame(g) {
  return { ...g, homeTeam: TEAMS[g.homeTeamId], awayTeam: TEAMS[g.awayTeamId] };
}

/* format helpers */
function fmtSpread(v) {
  if (Math.abs(v) < 0.5) return "PK";
  const r = Math.round(v * 2) / 2;
  return r > 0 ? `+${r}` : `${r}`;
}
function fmtML(v) { return v > 0 ? `+${v}` : `${v}`; }
function fmtDate(d) {
  const dt = new Date(d + "T12:00:00");
  return dt.toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric" });
}
